export const EDITPTSCANCEL = 'PTSCANCEL';
export const EDITTEAM1NAME = 'EDITTEAM1NAME';
export const EDITTEAM2NAME = 'EDITTEAM2NAME';
export const EDITBAGCOUNT = 'EDITBAGCOUNT';
export const EDITTARGETPTS = 'EDITTARGETPTS';
export const EDITINPTS = 'EDITINPTS';
export const EDITONPTS = 'EDITONPTS';
export const SAVEEDITS = 'SAVEEDITS';
export const DISCARDEDITS = 'DISCARDEDITS';

export const TYPES = {
    EDITPTSCANCEL,
    EDITTEAM1NAME,
    EDITTEAM2NAME,
    EDITBAGCOUNT,
    EDITTARGETPTS,
    EDITINPTS,
    EDITONPTS,
    SAVEEDITS,
    DISCARDEDITS
};